[project]
name = "video_clip"
version = "1.0.0"
requires-python = ">= 3.8"
dependencies = [
    "numpy",
    "opencv-python",
    "pillow",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = [""]